
-- #############################################################################
-- #                      create all the grands
-- #     select 'grant select on '||table_name||' to INTACT_SELECT ;'
-- #     from user_tables where table_name like 'V_%';
-- #############################################################################



SELECT 'GRANT SELECT, INSERT, UPDATE, DELETE ON '||table_name||' TO INTACT_SELECT;'
FROM user_tables WHERE table_name LIKE 'INTACT__%';

GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__EXPERIMENT__MAIN TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__FEATURE_ALIAS__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__FEATURE_ANNOTATION__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__FEATURE_ANNO__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__FEATURE_XREF__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__FEATURE__MAIN TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__HOSTORG_CELLTYPE__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__HOSTORG_TISSUE__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__INTERACTION_ALIAS__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__INTERACTION_ANNO__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__INTERACTION_XREF__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__INTERACTION__MAIN TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__INTERACTOR_ALIAS__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__INTERACTOR_ANNO__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__INTERACTOR_XREF__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__INTERACTOR__MAIN TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__PUBLICATION__DM TO INTACT_SELECT ;
GRANT SELECT, INSERT, UPDATE, DELETE ON INTACT__RANGE__DM TO INTACT_SELECT ;




-- #############################################################################
-- #                      create all the synonyms
-- #     select 'grant select on '||table_name||' to INTACT_SELECT ;'
-- #     from user_tables where table_name like 'V_%';
-- #############################################################################

SELECT 'CREATE OR REPLACE PUBLIC SYNONYM '||table_name||' FOR INTACT.' || table_name || ';'
FROM user_tables WHERE table_name LIKE 'INTACT__%';


CREATE OR REPLACE PUBLIC SYNONYM INTACT__EXPERIMENT__MAIN FOR INTACT.INTACT__EXPERIMENT__MAIN;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__FEATURE_ALIAS__DM FOR INTACT.INTACT__FEATURE_ALIAS__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__FEATURE_ANNOTATION__DM FOR INTACT.INTACT__FEATURE_ANNOTATION__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__FEATURE_ANNO__DM FOR INTACT.INTACT__FEATURE_ANNO__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__FEATURE_XREF__DM FOR INTACT.INTACT__FEATURE_XREF__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__FEATURE__MAIN FOR INTACT.INTACT__FEATURE__MAIN;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__HOSTORG_CELLTYPE__DM FOR INTACT.INTACT__HOSTORG_CELLTYPE__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__HOSTORG_TISSUE__DM FOR INTACT.INTACT__HOSTORG_TISSUE__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__INTERACTION_ALIAS__DM FOR INTACT.INTACT__INTERACTION_ALIAS__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__INTERACTION_ANNO__DM FOR INTACT.INTACT__INTERACTION_ANNO__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__INTERACTION_XREF__DM FOR INTACT.INTACT__INTERACTION_XREF__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__INTERACTION__MAIN FOR INTACT.INTACT__INTERACTION__MAIN;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__INTERACTOR_ALIAS__DM FOR INTACT.INTACT__INTERACTOR_ALIAS__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__INTERACTOR_ANNO__DM FOR INTACT.INTACT__INTERACTOR_ANNO__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__INTERACTOR_XREF__DM FOR INTACT.INTACT__INTERACTOR_XREF__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__INTERACTOR__MAIN FOR INTACT.INTACT__INTERACTOR__MAIN;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__PUBLICATION__DM FOR INTACT.INTACT__PUBLICATION__DM;
CREATE OR REPLACE PUBLIC SYNONYM INTACT__RANGE__DM FOR INTACT.INTACT__RANGE__DM;

