-- #############################################################################
-- #                      create all the grands
-- #     select 'grant select on '||table_name||' to INTACT_SELECT ;'
-- #     from user_tables where table_name like 'V_%';
-- #############################################################################


SELECT 'GRANT SELECT ON '||table_name||' TO INTACT_SELECT;'
FROM user_tables WHERE table_name LIKE 'V_%';


GRANT SELECT ON V_PUBLICATION_COUNTS TO INTACT_SELECT;
GRANT SELECT ON V_INTERACTION TO INTACT_SELECT;
GRANT SELECT ON V_INTERACTOR_OWNER TO INTACT_SELECT;
GRANT SELECT ON V_INTERACTOR_COUNT TO INTACT_SELECT;
GRANT SELECT ON V_INTERACTION_TYPE TO INTACT_SELECT;
GRANT SELECT ON V_INTERACTION_COUNT TO INTACT_SELECT;
GRANT SELECT ON V_EXPERIMENT TO INTACT_SELECT;
GRANT SELECT ON V_CV_MI TO INTACT_SELECT;
GRANT SELECT ON V_CV_PRIMARYID TO INTACT_SELECT;







-- #############################################################################
-- #                      create all the synonyms
-- #     select 'grant select on '||table_name||' to INTACT_SELECT ;'
-- #     from user_tables where table_name like 'V_%';
-- #############################################################################

SELECT 'CREATE OR REPLACE PUBLIC SYNONYM '||table_name||' FOR INTACT.' || table_name || ';'
FROM user_tables WHERE table_name LIKE 'V_%';



CREATE OR REPLACE PUBLIC SYNONYM V_PUBLICATION_COUNTS FOR INTACT.V_PUBLICATION_COUNTS;
CREATE OR REPLACE PUBLIC SYNONYM V_INTERACTOR_OWNER FOR INTACT.V_INTERACTOR_OWNER;
CREATE OR REPLACE PUBLIC SYNONYM V_INTERACTOR_COUNT FOR INTACT.V_INTERACTOR_COUNT;
CREATE OR REPLACE PUBLIC SYNONYM V_INTERACTION_TYPE FOR INTACT.V_INTERACTION_TYPE;
CREATE OR REPLACE PUBLIC SYNONYM V_INTERACTION_COUNT FOR INTACT.V_INTERACTION_COUNT;
CREATE OR REPLACE PUBLIC SYNONYM V_EXPERIMENT FOR INTACT.V_EXPERIMENT;
CREATE OR REPLACE PUBLIC SYNONYM V_CV_MI FOR INTACT.V_CV_MI;
CREATE OR REPLACE PUBLIC SYNONYM V_CV_PRIMARYID FOR INTACT.V_CV_PRIMARYID;
CREATE OR REPLACE PUBLIC SYNONYM V_PUBLICATION_MI FOR INTACT.V_PUBLICATION_MI;
CREATE OR REPLACE PUBLIC SYNONYM V_PUBLICATION_DOI FOR INTACT.V_PUBLICATION_DOI;
CREATE OR REPLACE PUBLIC SYNONYM V_PUBLICATION_PMID FOR INTACT.V_PUBLICATION_PMID;



